project:
  type: book

book:
  title: "./quarto_project"
  author: "Your name"
  date: "6/1/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - python_test.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

jupyter: python3

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



