name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      # - uses: DeterminateSystems/magix-nix-cache-action@main
      - name: Enter devshell
        run: nix develop --no-pure-eval
      - name: Build PDF
        run: quarto render --to pdf
      - name: Build HTML
        run: quarto render

